spring:
  datasource:
    url: jdbc:mysql://springboot-db.cjag6bqzspsc.ap-northeast-2.rds.amazonaws.com:3306/ordersystem
    username: admin
    password: skstjdrb!1

  jpa:
    hibernate:
      ddl-auto: update